version: '3'

services:

  mysql_database:
    image: mysql:8.0.2
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: curl --fail -s http://0.0.0.0:3308 || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "3308:3306"
    expose:
      - '3308'


  flaskapp:
    image: flaskapp
    container_name: flaskapp
    environment:
      DATABASE_URL: ${DATABASE_URL}
    expose:
      - '8080'
    depends_on:
      - mysql_database
    healthcheck:
      test: curl --fail -s http://0.0.0.0:8080 || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
    # Build app using Dockerfile in the same directory
    build: .
    ports:
      - '8080:8080'
