# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
       - uses: actions/checkout@v2
       - name: Build the docker-compose stack
         run: docker-compose up -d
       - name: Images
         run: docker images
       - name: Check running containers
         run: docker ps
       - name: Check all processes
         run: docker-compose ps -a
       - name: Check logs
         run: doocker-compose logs flaskapp
       - name: Test with pytest
         run: docker-compose exec -T flaskapp pytest
#       - name: docker login
#         env:
#           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#         run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#       - name: Push
#         run: |
#           VERSION=$(date +%s)
#           docker push ${{ secrets.DOCKER_USERNAME }}/yayloh:flaskapp_${VERSION}
##           docker push ${{ secrets.DOCKER_USERNAME }}/mysql:8.0.2:db










#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Build and push Docker images
#        uses: docker/build-push-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#          registry: docker.io
#          repository: atom13/yayloh
#          tags: v1
#  run_app:
#    container:
#      image: python:3.6-alpine
#      ports: 8080
#      options: --net
#
#      steps:
#        - name: Docker login
#          run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#        - name: Build
#          run: docker run -it -d -p 8080:8080 atom13/yayloh:flaskapp
#        - name: Push
#          run: docker push ${{ secrets.DOCKER_USERNAME }}/yayloh:v2

      
